### ISSUE TITLE
Error in simulating shift circuit

### ISSUE THREAD

**Issue by adamdai** [phanrahan/magma#212]
When using the magma simulator to simulate circuit in ice40:
```
from magma import *
set_mantle_target("ice40")
from mantle import*
from magma.simulator import PythonSimulator
from bit_vector import BitVector

Shift = DefineLSL(8, 4)
print(Shift)
lsl_sim = PythonSimulator(Shift)

#high = uint(0x01,8)
high = BitVector(0x01,8)
low = uint(0x02,8)

lsl_sim.set_value(Shift.I, high)
lsl_sim.evaluate()
print(lsl_sim.get_value(Shift.O))
```
I get the following error 
```
Traceback (most recent call last):
  File "/home/adam/magmathon/magma/magma/transforms.py", line 41, in get_new_bit
    return self.orig_to_new[QualifiedBit(bit=orig_bit, scope=scope)]
KeyError: QualifiedBit(bit=FixedLSL8_4.I[4], scope=<magma.scope.Scope object at 0x7f0fcdc80d30>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 33, in <module>
    lsl_sim.set_value(Shift.I, high)
  File "/home/adam/magmathon/magma/magma/simulator/python_simulator.py", line 282, in set_value
    newbit = self.txfm.get_new_bit(bit, scope)
  File "/home/adam/magmathon/magma/magma/transforms.py", line 32, in get_new_bit
    arr.append(self.get_new_bit(o, scope))
  File "/home/adam/magmathon/magma/magma/transforms.py", line 43, in get_new_bit
    raise MagmaTransformException("Could not find bit in transform mapping. bit={}, scope={}".format(orig_bit, scope))
magma.transforms.MagmaTransformException: Could not find bit in transform mapping. bit=FixedLSL8_4.I[4], scope=<magma.scope.Scope object at 0x7f0fcdc80d30>
```

**Comment by leonardt** [comment]
Fixed by 4723508. Simulator did not support inputs that were not wired up (in this case we drop the bits that are not used in the shift, so they are left unwired).

Also added this as a test to the mantle test suite https://github.com/phanrahan/mantle/commit/0bbd637a65b126333b05b29ac8c7a8673c9a646c
