### ISSUE TITLE
[Bug] Extension fails on undirected types

### ISSUE THREAD

**Issue by leonardt** [phanrahan/magma#293]
Example:
```
>>> a = m.Bits(2)()
>>> m.zext(a, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lenny/repos/magma/magma/conversions.py", line 196, in zext
    return concat(zeros, value)
  File "/Users/lenny/repos/magma/magma/conversions.py", line 177, in concat
    return array(ts)
  File "/Users/lenny/repos/magma/magma/conversions.py", line 156, in array
    return convertbits(value, n, ArrayType, Array, False)
  File "/Users/lenny/repos/magma/magma/conversions.py", line 150, in convertbits
    }[T.direction](Bit)
KeyError: None
```

**Comment by leonardt** [comment]
Closing in favor of https://github.com/phanrahan/magma/issues/295, extension only really makes sense on output values.
