### ISSUE TITLE
pip install broken for non-editable mode

### ISSUE THREAD

**Issue by rsetaluri** [phanrahan/magma#358]
On the latest version seeing:

```
>>> import magma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/magma/__init__.py", line 37, in <module>
    from .circuit import *
  File "/usr/local/lib/python3.7/site-packages/magma/circuit.py", line 572, in <module>
    from magma.syntax.combinational import combinational
ModuleNotFoundError: No module named 'magma.syntax'
```

**Comment by rsetaluri** [comment]
Was a confusion between magma-lang and magma. Oops :).
