### ISSUE TITLE
Can't import magma after upgrading to 0.1.17

### ISSUE THREAD

**Issue by Kuree** [phanrahan/magma#360]
See the build log: https://travis-ci.com/StanfordAHA/garnet/builds/101882320#L850-L861

Using the newest magma 0.1.17: https://travis-ci.com/StanfordAHA/garnet/builds/101882320#L822

EDIT: Add minimal example
```
$ pip install magma-lang
$ pip freeze
astor==0.7.1
bit-vector==0.42a0
colorlog==4.0.2
coreir==1.0.0
graphviz==0.10.1
magma-lang==0.1.17
Mako==1.0.7
MarkupSafe==1.1.0
numpy==1.16.1
six==1.12.0
$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import magma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/env/lib/python3.6/site-packages/magma/__init__.py", line 37, in <module>
    from .circuit import *
  File "/tmp/env/lib/python3.6/site-packages/magma/circuit.py", line 572, in <module>
    from magma.syntax.combinational import combinational
  File "/tmp/env/lib/python3.6/site-packages/magma/syntax/__init__.py", line 1, in <module>
    from magma.syntax.combinational import combinational
  File "/tmp/env/lib/python3.6/site-packages/magma/syntax/combinational.py", line 14, in <module>
    from magma.ssa import convert_tree_to_ssa
ModuleNotFoundError: No module named 'magma.ssa'
```

**Comment by leonardt** [comment]
Should be fixed by https://github.com/phanrahan/magma/commit/74a7bd6624c7e5e355c258303a778877423fe0aa, please reopen if that's not the case (it will take a moment for the new release to propagate).
