### ISSUE TITLE
Magma/Mantle Operators on Bit

### ISSUE THREAD

**Issue by phanrahan** [phanrahan/magma#456]
The following code fails.
```
import magma as m
import mantle
b = m.Bit(1)
b == False

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hanrahan/git/mantle/mantle/common/operator.py", line 43, in wrapped
    check_widths(width, args)
  File "/Users/hanrahan/git/mantle/mantle/common/operator.py", line 31, in check_widths
    (isinstance(arg, int) and arg_len < width)):
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```
This could also be considered a mantle bug.

Seems like we don't have tests for many of the mantle `Bit` operators.

**Comment by leonardt** [comment]
This works now
