### ISSUE TITLE
Duplicated port names allowed by magma

### ISSUE THREAD

**Issue by rsetaluri** [phanrahan/magma#554]
e.g.
```python
Foo = m.DeclareCircuit("Foo", "I", m.In(m.Bit), "I", m.In(m.Bit))
```
works, and `Foo.interface.ports` returns `OrderedDict([('I', Foo.I)])` implying one port is silently dropped.

We should report/error on this.

**Comment by leonardt** [comment]
This has been fixed with the introduction of the `m.IO` pattern:

```python
>>> class Foo(m.Circuit):
...     io = m.IO(a=m.In(m.Bit), a=m.In(m.Bit))
...
  File "<stdin>", line 2
SyntaxError: keyword argument repeated
>>> class Foo(m.Circuit):
...     io = m.IO(a=m.In(m.Bit))
...     io += m.IO(a=m.In(m.Bit))
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in Foo
  File "/Users/lenny/repos/magma/magma/interface.py", line 411, in __iadd__
    return self + other
  File "/Users/lenny/repos/magma/magma/interface.py", line 472, in __add__
    raise Exception("Adding IO with duplicate port names not allowed")
Exception: Adding IO with duplicate port names not allowed
```
